### ISSUE TITLE
COGReader -> Reader

### ISSUE THREAD

**Issue by vincentsarago** [sogelink-research/ctod#1]
First, this project looks great 😍, I'm sorry to open an issue (I don't have time to open a PR 😓) but `COGReader` is kinda deprecated and was replaced by `rio_tiler.io.Reader` in 4.0 (It's might be deleted at some point) 

https://github.com/sogelink-research/ctod/blob/c704908b45b2add020c03cdb1db9d854eff61c76/ctod/core/cog/cog.py#L3

see https://github.com/cogeotiff/rio-tiler/blob/main/rio_tiler/io/__init__.py#L8-L9

**Comment by tebben** [comment]
Thanks for the heads up and the positive feedback! COGReader is now updated to rio_tiler.io.Reader.
