### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by ankitpentashield** [sogelink-research/ctod#15]
![Screenshot 2024-09-05 140053](https://github.com/user-attachments/assets/b2784bbc-54a6-421f-af7c-042b3d797172)

**Comment by tebben** [comment]
![image](https://github.com/user-attachments/assets/9b47c479-d9c1-4bdc-93fd-c2af912c3327)

**Comment by tebben** [comment]
Again... Just throwing in images expecting something to happen
