### ISSUE TITLE
MacOS notes, DSM test tif

### ISSUE THREAD

**Issue by mhaberler** [sogelink-research/ctod#2]
phenomenal project, thanks!

I tried on a Mac M1 MB and wrote up some notes here:  https://github.com/mhaberler/ctod/blob/main/README-macos.md

I assume this works with a [vrt](https://gdal.org/drivers/raster/vrt.html) of a set of COG GeoTIFFs, right?

ps: should this go to Discussions?

**Comment by tebben** [comment]
Appreciate it! An issue report is sufficient; no need for a discussion.

Unfortunately, I don't have access to a Mac for testing but good to hear that you could get it to work.

I've validated that a VRT should function properly. I tested clipping two TIFFs with a gap between them, created a VRT, and successfully added it to the viewer. You can view the result in this image: 
![image](https://github.com/sogelink-research/ctod/assets/6178776/47c61214-ab0f-41d4-9724-999a8e21b1f2)

I noticed in your readme that the process seems slow with the TIFF you're testing. We're encountering a similar issue with a 320GB COG and are currently looking to find a solution.

**Comment by mhaberler** [comment]
I saw you used Python 3.10, will try that later - maybe the triangle module for 3.10 is ok on pypi

great to hear the VRT feature works! 

since all the 55 or so DSM tiles for Austria are HTTP-accessible I'll try a VRT with all of those and post results

that's a huge step forward for me - previously I had used tumgis/ctb-tiler but ran into size/memory limitations so could only use a small patch of a province -  that limit is removed!

happy to act as MacOS guinea pig!

**Comment by mhaberler** [comment]
re: performance: 

does the projection come into play? 

my COG dataset is EPSG 3035 - would a gdalwarp to 4326 or 3857 potentially help?

**Comment by tebben** [comment]
Tomorow we will conduct some performance tests on a COG with different projections/overviews/etc and report back to you with the results.

The performance for the COG mentioned in your readme doesn't look that bad, here is a video running it on my machine with caching disabled:

https://github.com/sogelink-research/ctod/assets/6178776/49f38f12-62f9-481d-85d3-48511474460f

**Comment by mhaberler** [comment]
that's much faster visually than my local experiment

seems like the HTTP access is not the issue
I'll have an eye on it

**Comment by mhaberler** [comment]
here's another DTM source which I've been using for a while with Cesium and ctb-tiler, pretty well maintained: https://sonny.4lima.de/ 

I plan to use those with ctod as a replacement for parts of Cesium World Terrain via ION

Those are GeoTIFF's which were to massaged into COG GeoTIFF's like so:

`````
# create overview
gdaladdo -r average input.tif 2 4 8 16  
# convert to COG GeoTIFF
gdal_translate -co  BIGTIFF=YES -co TILED=YES -co COMPRESS=DEFLATE -co COPY_SRC_OVERVIEWS=YES input.tif output
`````

the files are publicallly accessible with CORS headers via: https://static.mah.priv.at/cors/sonny-dtm-cog/ and the links can be pasted into the ‘cog’ field of the viewer

**Comment by tebben** [comment]
Closing this issue and continuing in issue: https://github.com/sogelink-research/ctod/issues/6 for performance problems
