### ISSUE TITLE
titiler integration / similar Monticello project

### ISSUE THREAD

**Issue by AndrewAnnex** [sogelink-research/ctod#4]
Hey all, first I just want to say I was able to successfully test the project locally on a m1 mac using orbstack fairly quickly and I am impressed by the work done so far. 

I was interested in asking about what the long term goals of this project are, as I had started a similar project called Monticello (https://github.com/AndrewAnnex/monticello/) but I am not funded to work on it and maybe I could contribute to this project instead of copying back functionality as you are all further along than me at this point. One way I could contribute to start is that I already implemented support for pymartini in my project so I could work on that contribution. 

My project differs in one major way which was to integrate with [titiler](https://github.com/developmentseed/titiler), and I was curious if that was considered for this project. I can see pros and cons at this point for making that change for sure though.

For my project the other goal was to support a wider range of CRSs (particularly for the Moon and planets like Mars) which in principal are supported by the 3D tiles specification although may not work directly with Cesium and instead projects like [3DTilesRendererJS](https://github.com/NASA-AMMOS/3DTilesRendererJS) may support more directly. As I am fairly new to the cesium format/3d tiles spec I am not sure I am well equipped to quickly add support for additional CRSs without some guidance, but I can certainly help with testing and validation, providing example datasets, etc.

let me know your thoughts and thanks!

**Comment by bertt** [comment]
Hi, for terrains of various planets see https://www.terrainserver.com/ (uses CesiumJS) maybe good for inspiration
