### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by tebben** [sogelink-research/ctod#6]
Do some benchmarking to see what COG settings have an effect on the performance and show how can we prepare a COG to have the best performance possible.

**Comment by tebben** [comment]
When a cog has not enough overviews, rio-tiler/rasterio needs to request multiple tiles which can get out of hand and can result in requests taking minutes to be handled. 

With this commit:
https://github.com/sogelink-research/ctod/commit/c435d06e55fbed71a5cfbcb1ba5375986930be1a we introduce a check if it's safe to load a tile based on the requested tile and dataset downsampling. When it is not safe to load a tile it will be skipped and return an empty tile and a warning will be displayed to generate more overviews.

```sh
2024-01-22 13:00:52 | WARNING | Skipping https://data.bev.gv.at/download/ALS/DSM/20220915/ALS_DSM_CRS3035RES50000mN2650000E4750000.tif (6, 69, 16), tile is not safe to load, generate more overviews
```

Impact of overviews/projection/tms in COG is currently being tested.

**Comment by mhaberler** [comment]
any recommendations for a known-good gdaladdo argument list?

I used

`````
gdaladdo -r average input.tif 2 4 8 16  
`````
which worked - anything to improve here?

**Comment by tebben** [comment]
We are still testing some things but projecting to 4326 and using the same tiling schema as used by Cesium seems to performs nicely.

Warp to 4326

```sh
gdalwarp -t_srs EPSG:4326 R_09BN2.TIF R_09BN2_4326.TIF
```

Create COG

```sh
rio cogeo create R_09BN2_4326.TIF R_09BN2_4326_cog.tif --cog-profile deflate --blocksize 256 --overview-blocksize 256 --tms ./WGS1984Quad.json
```

However when we profile a tile request using (a slightly modified) [tilebench](https://github.com/developmentseed/tilebench) we expect 2 GET request: header+data but it reports 4 requests. This is possibly because the internal tiles do not perfectly align correctly with the tile bounds.

```sh
tilebench profile http://localhost:3000/R_09BN2_4326_cog.tif --tile 17-134586-26855 --add-kernels | jq
```

```sh
{
  "HEAD": {
    "count": 1
  },
  "GET": {
    "count": 4,
    "bytes": 632003,
    "ranges": [
      "0-65535",
      "259176040-259439830",
      "265677443-265980118"
    ]
  },
  "WarpKernels": [],
  "Timing": 0.025652170181274414
}

```

We also tried a big VRT with 1000's of cogs which doesn't work at the moment.

**Comment by tebben** [comment]
Opened issue at rio-cogeo: https://github.com/cogeotiff/rio-cogeo/issues/275

**Comment by mhaberler** [comment]
I fetched two adjacent ALS DSM's from https://bev.gv.at:

wget https://data.bev.gv.at/download/ALS/DSM/20220915/ALS_DSM_CRS3035RES50000mN2650000E4750000.tif
wget https://data.bev.gv.at/download/ALS/DSM/20220915/ALS_DSM_CRS3035RES50000mN2650000E4700000.tif

reprojected with `gdalwarp -t_srs EPSG:4326 <in> <out>`

created cog's:

`rio cogeo create ALS_DSM_CRS3035RES50000mN2650000E4700000-4326.tif ALS_DSM_CRS3035RES50000mN2650000E4700000-4326-cog.tif  --cog-profile deflate 
--blocksize 256 --overview-blocksize 256 --tms  WGS1984Quad.json`



The individual *4326-cog.tif files render in the viewer, and perform nicely

however, they are still unsafe?
````
(venv) BigM1:ctod mah$ python app.py --tile-cache-path ./ctod_cache --logging-level info --port 5001 --unsafe
2024-01-24 10:12:40 | INFO | -----------------------
2024-01-24 10:12:40 | INFO | CTOD Started
2024-01-24 10:12:40 | INFO | -----------------------
2024-01-24 10:12:40 | INFO | Port: 5001
2024-01-24 10:12:40 | INFO | Caching: enabled
2024-01-24 10:12:40 | INFO | Caching Path: ./ctod_cache
2024-01-24 10:12:40 | INFO | -----------------------
2024-01-24 10:13:05 | WARNING | Loading unsafe tile ./ctod/files/ALS_DSM_CRS3035RES50000mN2650000E4750000.tif (2, 4, 0), consider generating more overviews
2024-01-24 10:13:05 | WARNING | Loading unsafe tile ./ctod/files/ALS_DSM_CRS3035RES50000mN2650000E4750000.tif (2, 3, 0), consider generating more overviews
...
````

create VRT:
````
(venv) BigM1:files mah$ gdalbuildvrt stmk.vrt *-4326-cog.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
````

rendering the VRT causes an exception:
`````
ValueError: max() arg is an empty sequence
2024-01-24 10:37:26 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-198' coro=<TerrainFactory._process_completed_cog_request() done, defined at /Users/mah/Ballon/src/ctod/ctod/core/factory/terrain_factory.py:84> exception=ValueError('max() arg is an empty sequence')>
Traceback (most recent call last):
  File "/Users/mah/Ballon/src/ctod/ctod/core/factory/terrain_factory.py", line 85, in _process_completed_cog_request
    await future  # Wait for the completion of the future
    ^^^^^^^^^^^^
  File "/Users/mah/Ballon/src/ctod/ctod/core/cog/cog_request.py", line 56, in download_tile_async
    reader = await self.cog_reader_pool.get_reader(self.cog, self.tms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mah/Ballon/src/ctod/ctod/core/cog/cog_reader_pool.py", line 39, in get_reader
    reader = CogReader(self, cog, tms, self.unsafe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mah/Ballon/src/ctod/ctod/core/cog/cog_reader.py", line 21, in __init__
    self._set_safe_level()
  File "/Users/mah/Ballon/src/ctod/ctod/core/cog/cog_reader.py", line 89, in _set_safe_level
    pixels_per_tile_downsampled = 256 * max(self.rio_reader.dataset.overviews(1))
`````

is the ordering correct: `gdalwarp -> rio cogeo create -> gdalbuildvrt` ?


Versions:
`````
(venv) BigM1:ctod mah$ rio cogeo --version
5.1.1

(venv) BigM1:ctod mah$ rio --version
1.3.9

(venv) BigM1:ctod mah$ gdalwarp --version
GDAL 3.8.3, released 2024/01/04
`````

I can upload artefacts if needed

**Comment by tebben** [comment]
When not supplying `--overview-level` to rio cogeo your COG at overview 8 does not fit in 1 tile (259 slightly larger than 1 tile in width) when you request low zoom levels, something between 0-7.

```sh
1_4326_cog.tif overviews

    Id      Size           BlockSize     Decimation           
    0       66304x45312    256x256       0
    1       33152x22656    256x256       2
    2       16576x11328    256x256       4
    3       8288x5664      256x256       8
    4       4144x2832      256x256       16
    5       2072x1416      256x256       32
    6       1036x708       256x256       64
    7       518x354        256x256       128
    8       259x177        256x256       256

```

There was also a small error in the `unsafe` check and i loosened the check a bit, it is fine that a COG request internally requests a few more tiles but without the check it can potentially request 100's of tiles internally. With the update you should not get the warnings anymore for the COG you created without `--overview-level`

***VRT Test***

The steps i took to download/warp/create cog and build a vrt file.

```sh
wget https://data.bev.gv.at/download/ALS/DSM/20220915/ALS_DSM_CRS3035RES50000mN2650000E4750000.tif
wget https://data.bev.gv.at/download/ALS/DSM/20220915/ALS_DSM_CRS3035RES50000mN2650000E4700000.tif

mv ALS_DSM_CRS3035RES50000mN2650000E4750000.tif 1.tif
mv ALS_DSM_CRS3035RES50000mN2650000E4700000.tif 2.tif

gdalwarp -t_srs EPSG:4326 1.tif 1_4326.tif
gdalwarp -t_srs EPSG:4326 2.tif 2_4326.tif

rio cogeo create 1_4326.tif 1_4326_cog.tif --cog-profile deflate --blocksize 256 --overview-blocksize 256 --tms ./WGS1984Quad.json -w --overview-level 10 --aligned-levels 9 --no-in-memory

rio cogeo create 2_4326.tif 2_4326_cog.tif --cog-profile deflate --blocksize 256 --overview-blocksize 256 --tms ./WGS1984Quad.json -w --overview-level 10 --aligned-levels 9 --no-in-memory

gdalbuildvrt dataset.vrt 1_4326_cog.tif 2_4326_cog.tif
```

The vrt seems to work fine with everything running locally http://localhost:5000/?cog=http://localhost:3000/dataset.vrt I can see data from both cogs and it perfoms pretty great. Warning: I'm not sure how optimal above creation options are and still looking into many cogs in the vrt file.

both cogs loaded using the vrt
![image](https://github.com/sogelink-research/ctod/assets/6178776/ec08b67b-5e08-4795-80e5-ca4aea0cd027)

**Comment by mhaberler** [comment]
thanks, really appreciated!

**Comment by mhaberler** [comment]
I converted all 55 DSM tiles for Austria from source above, and made them [available here](https://static.mah.priv.at/cors/terrain/DSM/AT-1m/?C=S&O=A) - total of 292GB, plus a [relative VRT](https://static.mah.priv.at/cors/terrain/DSM/AT-1m/all.vrt) - feel free to test, has CORS headers (NB: I observed temp file sizes above 250GB during the conversion with `rio cogeo create`)

There's something I cant quite explain:
- running ctod on an M1 Mac with 64GB: superfast, very quick zooming in and out
- running ctod on a 16GB x86_64 linux box - same config: zoom in/out and the working set of the ctod process goes through the roof (use this [link for now](https://ctod.mah.priv.at/?cog=./ctod/files/AT-DSM-1m.vrt), I'll have to disable it eventually)
- I dont have a 64GB x86_64 at hand - memory might be the cause but not sure

can you give these cogs a spin on x86_64?

**Comment by tebben** [comment]
Thanks for testing some things out. I have no idea what is happening internally when using a VRT, when I try to profile getting a tile using tilebench

```sh
tilebench profile http://localhost:3000/mhaberler.vrt --tile 19-563250-124861 --add-kernels --tms ./WGS1984Quad.json| jq
```

It runs for quite a while and I see my network going up to 12MB/s during the whole request and ends in an error. Trying to load it into QGIS freezes my whole system.

rio-tiler mentions: ***Map Tile reading from VRT might not be efficient if overviews are not present, because GDAL will try to open a lot of files.*** The vrt reports overviews and there are overviews available in the referenced COG's, so I'm not sure why it tries to load a huge amount of data.

With rio-tiler we should also be able to use [https://cogeotiff.github.io/rio-tiler/mosaic/](https://cogeotiff.github.io/rio-tiler/mosaic/) The thing is that the creation of a mosaic json uses Quadkey which does not work with the TMS we are using. In theory this should still work but is not the most optimal. 

I want to try to create a simple bash script to create a json with info on the datasets and in the reader part do my own selection of datasets and feed it to the mosaic reader and see how that works out.

**Comment by mhaberler** [comment]
thanks!

re overviews - the current tifs were created with
`````
....
for fn in $*
do
    base=`basename $fn .tif`
    echo warping $base
    
    gdalwarp -t_srs EPSG:4326 $fn tmp.tif
    echo create cog for $base
    time rio cogeo create tmp.tif $target/${base}-cog.tif  --cog-profile deflate --blocksize 256 --overview-blocksize 256 --tms $wgsquad  -w --overview-leve
l 10 --aligned-levels 9  --no-in-memory
    rm -f tmp.tif
done
gdalbuildvrt bev-als-dsm.vrt $target/*.tif
`````
prepared to retry with other suggestions - all of Austria takes over a day though

**Comment by TomvanTilburg-geodan** [comment]
@mhaberler , it seems that gdal->rasterio doesn't treats the tiffs as COGS when you don't add  `/vsicurl/` in front of every url, and hence tries to read every tiff in its entirety before producing tiles. 
So the fix for a slow or non-performing vrt might be to make every `https://etcetera` into `/vsicurl/https://etcetera`
I tested this for your Austrian data and it works for me at reasonable speed now with CTOD.

**Comment by mhaberler** [comment]
wow.. great find! where did you dig that out?

so I assume in that case cog's overviews are ignored - that explains what I see

in that case the more interesting topic will be why this really zips on the Mac M1.. will have a look

should have results to report in a few days.

ps: plus my server being added an 8TB ssd shortly so there's leeway for experimentation :)

**Comment by TomvanTilburg-geodan** [comment]
> in that case the more interesting topic will be why this really zips on the Mac M1.. will have a look
sounds like it could be different versions of gdal. Would be interesting to find out, you might dig into gdal changelogs...

**Comment by mhaberler** [comment]
will check and report

**Comment by mhaberler** [comment]
step1:

upgraded GDAL by [selecively installing from testing](https://unix.stackexchange.com/questions/439073/how-to-pull-a-single-or-few-packages-from-debian-testing-to-debian-oldstable), as it's a bookworm/stable production box
GDAL now at  3.8.3

`vsicurl` change as suggested above not yet applied

result:

working set signifcantly reduced, usability sort of ok in in-cache regions
fluidity still far off from Mac M1 experience

`vsicurl` change is next

**Comment by mhaberler** [comment]
@TomvanTilburg-geodan do you have a syntax example how to change the .vrt file ?

or a command line example for gdalbuildvrt ?

my current (relative) .vrt has references like so:
`      <SourceFilename relativeToVRT="0">/junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/ALS_DSM_CRS3035RES50000mN2550000E4650000-cog.tif</SourceFilename>`

**Comment by TomvanTilburg-geodan** [comment]
> @TomvanTilburg-geodan do you have a syntax example how to change the .vrt file ?

I just used a search and replace in my favourite text editor ;-) 
My plan is to automize this via a bash script.

**Comment by tebben** [comment]
In the latest CTOD version I check if a given VRT should be loaded from an URL and if so add url's to the referenced files automatically, it also adds /vsicurl/ in front of the URL. So creating a vrt with relative paths should automatically work if the .vrt file is hosted in the same location as the files. When requesting a tile with the file locally (?cog=/home/user/dataset.vrt) it only changes the file references if it references a dataset with http/https by adding /vsicurl/. This way you won't have to do anything special when creating a vrt file.

I was hoping to see some fast country wide terrain using a vrt with these changes but unfortunately I don't see much improvement on my machine, I can still spot heavy network traffic. I also tried updating GDAL from 3.4.1 to 3.6.4. VRT needs still needs some more digging....

I also added support for mosaic. The mosaic should be more performant than the vrt because I'm reusing the readers for the different cogs. Later on mosaic also can be used to calculate on multiple tiff tiles when they overlap, like: highest/lowest/median/average or add priority. CTOD has it's own format for the JSON and does not support [mosaicjson-spec](https://github.com/developmentseed/mosaicjson-spec) since this only works with quadkeys.

a json can for now be created using the script: `scripts/create_mosaic.py` the extension can be `.ctod` or `.json` for it to be treated as a mosaic dataset.

```sh
python create_mosaic.py -i /home/user/cogs -o /home/user/cogs/mosaic.ctod --ignore-nodata
```

In the reader I check which cogs overlap with the requesting tile (this can be multiple files) and rio mosaic combines the data if necessary. When you create cogs and align the tiles it's possible that there will be large bounds around the actual data with nodata values, using the --ignore-nodata the 'real' bounds of the dataset will be used in the json file. When you don't add --ignore-nodata it still works but it's possible 2 tiles are requested where only 1 has data, which lowers the performance a bit. 

It looks very promising but I still have to test it out on a large dataset.

To be continued.

**Comment by tebben** [comment]
I just created a json (mosaic) for the dataset of @mhaberler but since I don't have the files locally i cannot use --ignore-nodata so it uses it's reported bounds from gdalinfo. I can see it trying to use data from 11 different files for 1 tile when zoomed in where it should probably use 1 file. Due to the overlapping data it is pretty slow. 

We should check if this is also a reason the vrt file is slow and what is causing the huge nodata around the files? overviews, aligned levels or a combination.

I Downloaded 1 file  with reported extent: `9.84375, 46.40625, 12.65625, 47.8125` and visualized the nodata with red in qgis.

![image](https://github.com/sogelink-research/ctod/assets/6178776/fb0576aa-20c4-44fe-86ec-c0763c6bc667)

**Comment by mhaberler** [comment]
@tebben mail me your public ssh key at haberlerm at gheemail;)

**Comment by mhaberler** [comment]
trying the  create_mosaic.py  suggestion now, looks like this will run a while

**Comment by mhaberler** [comment]
it's online:

> (venv) mah@mah2:~/src/ctod$ python scripts/create_mosaic.py -i /junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m -o /junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/mosaic.ctod --ignore-nodata
> Calculating extent excluding nodata, this can take some time: /junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/ALS_DSM_CRS3035RES50000mN2650000E4300000-cog.tif
> /home/mah/src/ctod/scripts/create_mosaic.py:56: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
>   indices = np.where(~data_array_masked.mask)
> Calculating extent excluding nodata, this can take some time: /junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/ALS_DSM_CRS3035RES50000mN2650000E4650000-cog.tif

....
should we bother about that warning

I restarted the service, not sure how to use this?

**Comment by tebben** [comment]
***Commited some changes***

Passing resampling to rio-tiler can lead to requesting much more data behind the scenes and slowing down the performance. Resampling now defaults to None instead of `bilinear`, this can lead to the terrain being blocky when passing the max zoom of the dataset. Consider setting the correct max zoom for your dataset or use the `resamplingMethod` with caution.

Max zoom now defaults to 18, most of the datasets don't go past 18 so this is a better default setting.

The geodetic surface normals for empty tiles were incorrect causing dark tiles, should be fixed now.

When loading a vrt or json/ctod dataset from url the refered datasets are now updated with the full path of the url instead of only the domain.

create_mosaic.py script should not throw the deprecated warning anymore.

creation of layer.json for mosaic can now use a local filepath.

@mhaberler 
If you update CTOD on your server to the latest version and make the paths in the mosaic absolute, you should be able to use the mosaic file like this:

[https://ctod.mah.priv.at/?cog=/junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/mosaic.ctod](https://ctod.mah.priv.at/?cog=/junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/mosaic.ctod)

When you supply a local filepath, the refered datasources are not updated and loaded from the local file system based on the path parameter. When the mosaic file is given as an url, the refered datasources are updated to be loaded over the internet automatically `https://ctod.mah.priv.at/?cog=https://static.mah.priv.at/cors/terrain/DSM/AT-1m/mosaic.ctod`

Since you have all the data locally on your server you should update the paths in the `.ctod` file to be relative to the ctod server or use the absolute path. I should update the create_mosaic script to accept some more parameters to set the correct path more easily. For now just do a find and replace: `"path": "` to `"path": "/junk/www/static.mah.priv.at/cors/terrain/DSM/AT-1m/` to make the paths absolute.

A new safe check was added for mosaic, when Cesium is requesting low zoom level tiles, it is possible terrain tiles are composed of multiple cogs, for now this cannot pass the 10 datasets per tile. If you want to work around this you can add --unsafe when starting CTOD or ignore low zoom levels by setting minZoom a bit higher.

**Comment by mhaberler** [comment]
followed your instructions, and the link you gave above works as given -  give it a try!

I noted some log messages like so:
````
2024-02-12T16:05:21.974730+01:00 ssl python[1072853]: 2024-02-12 16:05:21 | WARNING | Too many datasets intersecting with requested tile (7, 138, 30), 13
2024-02-12T16:05:21.980428+01:00 ssl python[1072853]: 2024-02-12 16:05:21 | WARNING | Too many datasets intersecting with requested tile (7, 137, 30), 11
2024-02-12T16:05:21.982170+01:00 ssl python[1072853]: 2024-02-12 16:05:21 | WARNING | Too many datasets intersecting with requested tile (7, 139, 30), 11
2024-02-12T16:05:42.343902+01:00 ssl python[1072853]: 2024-02-12 16:05:42 | WARNING | Too many datasets intersecting with requested tile (5, 34, 7), 45
2024-02-12T16:05:42.345005+01:00 ssl python[1072853]: 2024-02-12 16:05:42 | WARNING | Too many datasets intersecting with requested tile (5, 33, 7), 11
2024-02-12T16:05:44.385049+01:00 ssl python[1072853]: 2024-02-12 16:05:44 | WARNING | Too many datasets intersecting with requested tile (3, 8, 1), 55
2024-02-12T16:05:44.386258+01:00 ssl python[1072853]: 2024-02-12 16:05:44 | WARNING | Too many datasets intersecting with requested tile (2, 4, 0), 55
2024-02-12T16:05:53.691169+01:00 ssl python[1072853]: 2024-02-12 16:05:53 | WARNING | Too many datasets intersecting with requested tile (3, 8, 1), 55
2024-02-12T16:05:53.691976+01:00 ssl python[1072853]: 2024-02-12 16:05:53 | WARNING | Too many datasets intersecting with requested tile (2, 4, 0), 55
2024-02-12T16:05:54.682014+01:00 ssl python[1072853]: 2024-02-12 16:05:54 | WARNING | Too many datasets intersecting with requested tile (1, 2, 0), 55
2024-02-12T16:05:55.054027+01:00 ssl python[1072853]: 2024-02-12 16:05:55 | WARNING | Too many datasets intersecting with requested tile (5, 34, 7), 45
2024-02-12T16:05:55.054226+01:00 ssl python[1072853]: 2024-02-12 16:05:55 | WARNING | Too many datasets intersecting with requested tile (5, 33, 7), 11
2024-02-12T16:05:55.056152+01:00 ssl python[1072853]: 2024-02-12 16:05:55 | WARNING | Too many datasets intersecting with requested tile (4, 17, 3), 46
2024-02-12T16:05:55.056566+01:00 ssl python[1072853]: 2024-02-12 16:05:55 | WARNING | Too many datasets intersecting with requested tile (4, 16, 3), 11
````

**Comment by mhaberler** [comment]
I suspice ctod has a memory leak - vm size grows despite settling after idle periods

**Comment by tebben** [comment]
I added a [wiki page](https://github.com/sogelink-research/ctod/wiki/COG-Optimization) on how to optimise COG's. Later on I will  look into other solutions to boost the performance as stated in the [README](https://github.com/sogelink-research/ctod?tab=readme-ov-file#future-work-v11)

Closing this issue for now.
