### ISSUE TITLE
artefacts in COGs

### ISSUE THREAD

**Issue by mhaberler** [sogelink-research/ctod#8]
I noticed some artefacts in cogs, for example in [ALS_DSM_CRS3035RES50000mN2550000E4650000-cog.tif](https://static.mah.priv.at/cors/ALS_DSM_CRS3035RES50000mN2550000E4650000-cog.tif)
it was processed with:
````
    gdalwarp -t_srs EPSG:4326 <in> <warped>
    rio cogeo create <warped> <cog.tif>  --cog-profile deflate --blocksize 256 --overview-blocksize 256 --tms WGS1984Quad.json  -w --overview-level 10 --aligned-levels 9  --no-in-memory
`````

one must zoom out far to see them:
![Bildschirmfoto 2024-01-26 um 11 45 22](https://github.com/sogelink-research/ctod/assets/901479/3351f40e-485f-47b1-b252-402ce65b22d6)

a `rio cogeo create` bug?

**Comment by tebben** [comment]
Doesn't seem to be a problem with CTOD, closing
