### ISSUE TITLE
I suspice ctod has a memory leak - vm size grows despite settling after idle periods

### ISSUE THREAD

**Issue by tebben** [sogelink-research/ctod#9]
I suspice ctod has a memory leak - vm size grows despite settling after idle periods

_Originally posted by @mhaberler in https://github.com/sogelink-research/ctod/issues/6#issuecomment-1939671484_

**Comment by tebben** [comment]
Did alot of debugging but haven't found why memory is not released. 
The heap goes down but RSS just keeps increasing.

- Not using the caching mechanism -> No difference
- Not using the reader pool -> No difference
- Tried different GDAL settings, wrapping reader in gdal environment -> No difference
- Moving from tornado to fastapi for the web framework -> No difference
- Setting max workers per core to 1 -> No difference
 - Creating rio readers but not reading data from a COG (`reader.tile(...)`) and returning None instead -> Stable memory

The problem looks related to what is being discussed here: https://github.com/tiangolo/fastapi/discussions/9145

Next tests
- Return mock data from the cog reader so the whole process is tested without `reader.tile`
- Python 3.12 which has alot of improvements over 3.10

**Comment by tebben** [comment]
# Update

Getting closer to fix the issue.....

## Testing reader with .tif

Running idle without requests fired yet => 123MB

- Calling reader.tile and returning actual data: First load 271MB, memory not lowering when idle. Increasing memory when panning/zooming.
- Return None not calling reader.tile: First load 136MB, memory not lowering when idle. Memory only slightly increases when panning/zooming.
- Return mock data not calling reader.tile: First load 246MB, not lowering memory. Memory keeps increasing when panning/zooming.

## Testing reader with .ctod

When returning mock data and using .ctod file (mosaic reader) the first load is 259MB and lowers to 165MB. When panning/zooming to 813MB the memory is lowering to 649. It looks like with the mosaic reader some memory is being released but it looks like some can still get 'stuck'

With the above test it looks like `reader.tile` has the same effect as returning mock data and the problem should not be directly related to rio-tiler/rasterio/GDAL.

## Some more tests

- Manually clear everything in the cog_request when it gets deleted doesn't make a difference
- Not setting downloaded data in cog request keeps memory stable. The request will not go trough the processor
- Setting downloaded data in cog request but not processing the data increases memory which is mostly not released
- Copying over downloaded data and deleting the original data makes no difference
- deleting everything in terrain generator before returning quantized mesh makes no difference
- When a terrain request is done, make sure everything is cleared, makes no difference
- Calling terrain request process synchronous makes no difference

## Found something, or not...

When not spawning cog requests within the factory, not putting a cog request in the cache and not copying over data to terrain requests internal wanted files. This will run very slow because of the amount of request needed to run this but I'm not able to get the memory above 170MB.

However swappping over to the real data instead of the mock data, so calling `reader.tile` again. The memory is back to taking a huge amount and not decreasing when idle.

Suspecting the reuse of readers has impact aswell, disabled reusing the readers and memory was 155MB and after a lot of panning zooming it was around 157MB.

**Comment by tebben** [comment]
The changes for python 3.12 looked interesting memory/performance wise but couldn't get it to work with some dependencies. Python 3.11 didn't make a difference.

Still couldn't find out if it is realy a memory leak or the memory just not being released to the OS, it looks like eveything is getting destroyed accordingly.

With this update: https://github.com/sogelink-research/ctod/commit/372f1329fea3f0dc5e78b841a981d0a3f5493cc7 CTOD now uses FastAPI instead of Tornado, it was a test to see if it made any difference in memory usage which it didn't but it's a nice change to keep. The update also introduces file based cache for the TerrainFactory, the shared tiles are not stored in memory which makes a huge difference but seems to impact the performance a bit and some improvements can be done in a later stage. The nice thing with the TerrainFactory cache is that we can share state between workers and add support processing on more cores later on instead of the current 1 CPU core max currently.

When looking at the memory it still keeps increasing but at a much lower rate until it reaches a treshold which in my case is around 310MB, I suspect the GDAL cache. When not reading image data from a COG and returning np arrays with random height from the reader the memory always drops to 190MB after load in my test case. 

Closing this issue for now since the memory usage looks a lot better.

**Comment by tebben** [comment]
In a test running a continues stream of 20 parallel requests for different terrain tiles for 10 minutes I can see the memory bouncing between 350 - 410 MB. This is tested on a mosaic file containen 9 cogs. 

LGTM

**Comment by mhaberler** [comment]
that is much better!
it will be few days until I can update and test, but will definitely do that and report

**Comment by mhaberler** [comment]
updated my server

two questions:
- my box has 16 cores. Do I need to update this to 16? https://github.com/sogelink-research/ctod/blob/main/start_server.py#L19
- I suspice my COGs lack overviews - how do I tickle ctod to prime the cache ? (for a region?)

**Comment by tebben** [comment]
For now workers should stay at 1, for python to use more cores multiple instances of the service need to spin up which is currently not supported because there is no state yet which can be shared between the instances. Documentation on caching can be found on the [wiki](https://github.com/sogelink-research/ctod/wiki/Seeding-the-cache) you can create a new issue to add support for supplying a region to the seed script.

**Comment by mhaberler** [comment]
thanks!
